services:
  stasis-backend:
    build: .
    container_name: stasis-api
    ports:
      - "8080:8080"  # Bind to all interfaces so nginx can access it
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DATABASE_URL=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.pozbytnqdvelbsbrblle&password=rbbEbSyTuoK6kEew
      - DATABASE_USERNAME=postgres.pozbytnqdvelbsbrblle
      - DATABASE_PASSWORD=rbbEbSyTuoK6kEew
      - PORT=8080
      - SERVER_FORWARD_HEADERS_STRATEGY=framework  # Handle X-Forwarded headers properly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - stasis-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  stasis-network:
    driver: bridge
